### ISSUE TITLE
Incompatibility with current Open3D

### ISSUE THREAD

**Issue by mastrogiorgis** [timfelle/PointCloudRegistration#1]
Hi,

I'm trying to compile your code, but the include paths do not match the current Open3D header files.

The
#include <Open3D/IO/IO.h> 
#include <Open3D/Core/Core.h>
are not valid anymore.

Can you please advice?

Many thanks

**Comment by timfelle** [comment]
Hello,

I am not using Open3D in my daily work and i am not maintaining this repository actively so i am afraid i cannot help you solve the problem. This repo have been developed to work with Open3D version 0.4.0 so i suggest you use that version if you want to use this code. 

However, i suspect you could locate the following functions and classes in Open3D and change the headers accordingly.
- ComputeFPFHFeature
- WritePointCloud
- PointCloud

**Comment by timfelle** [comment]
Closed due to inactivity
